extends: eslint:recommended

rules:
    indent: [2, 4]
    linebreak-style: [2, unix]
    quotes: [2, double]
    semi: [2, always]
    comma-dangle: [2, always-multiline]
    no-unused-expressions: [2]
    prefer-arrow-callback: error
    object-shorthand: error
    prefer-template: error

globals:
    __DEV__: false

env:
    es6: true

parserOptions:
    sourceType: module
