extends: eslint:recommended

rules:
    indent: [2, 4]
    linebreak-style: [2, unix]
    quotes: [2, double]
    semi: [2, always]
    comma-dangle: [2, always-multiline]

env:
    es6: true
    node: true
